export const GET_POST = 'GET_POST';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const SELECTED_POST = "SELECTED_POST";
export const SELECTED_POST_SUCCESS = "SELECTED_POST_SUCCESS";
export const SELECTED_POST_ERROR = "SELECTED_POST_ERROR";

export const NEW_POST = "NEW_POST";
export const NEW_POST_SUCCESS = "NEW_POST_SUCCESS";
export const NEW_POST_ERROR = "NEW_POST_ERROR";

export const EDIT_POST = "EDIT_POST";
export const EDIT_POST_SUCCESS = "EDIT_POST_SUCCESS";
export const EDIT_POST_ERROR = "EDIT_POST_ERROR";

export const DELETE_POST = "DELETE_POST";
export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";